services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_DB: "shortner"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  service:
    container_name: service
    restart: always
    build:
      context: .
    environment:
      DATABASE_URL: "postgres://postgres:5432@postgres:5432/shortner"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:  
  pgdata: {}